# Generated by Django 5.1.5 on 2025-03-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0001_initial'),
        ('App_Entry', '0011_alter_item_unit_of_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_no', models.IntegerField(unique=True)),
                ('warehouse', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Entry.item')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Entry.package')),
                ('pbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Allocation.pbs')),
            ],
        ),
    ]
