# Generated by Django 5.1.5 on 2025-03-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0004_temporary_allocation_item_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary_allocation',
            name='item_primary_key',
            field=models.IntegerField(null=True),
        ),
    ]
