# Generated by Django 5.1.5 on 2025-03-05 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0005_alter_temporary_allocation_item_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_allocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 5, 19, 1, 34, 106316, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporary_allocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 5, 19, 1, 38, 636015, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
