# Generated by Django 5.1.5 on 2025-03-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0006_final_allocation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_allocation',
            name='item_primary_key',
            field=models.IntegerField(null=True),
        ),
    ]
