# Generated by Django 5.1.5 on 2025-03-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0007_final_allocation_item_primary_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_no', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='final_allocation',
            name='allocation_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Allocation.allocation_number'),
        ),
        migrations.AlterField(
            model_name='temporary_allocation',
            name='allocation_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Allocation.allocation_number'),
        ),
    ]
