# Generated by Django 5.1.5 on 2025-03-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0008_allocation_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_number',
            name='allocation_no',
            field=models.IntegerField(unique=True),
        ),
    ]
