# Generated by Django 5.1.5 on 2025-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0012_final_allocation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_allocation',
            name='status',
        ),
        migrations.AddField(
            model_name='allocation_number',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled')], default='Pending Approva', max_length=100),
        ),
    ]
