# Generated by Django 5.1.5 on 2025-03-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0013_remove_final_allocation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_number',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled')], default='Pending Approval', max_length=100),
        ),
    ]
