# Generated by Django 5.1.5 on 2025-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0014_alter_allocation_number_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation_number',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled'), ('Modified', 'Modified')], default='Pending Approval', max_length=100),
        ),
    ]
