# Generated by Django 5.1.5 on 2025-08-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0015_alter_allocation_number_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_allocation',
            name='unit_of_item',
            field=models.TextField(default='Mtr.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporary_allocation',
            name='unit_of_item',
            field=models.TextField(default='Mtr.'),
            preserve_default=False,
        ),
    ]
