# Generated by Django 5.1.5 on 2025-08-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Allocation', '0018_final_allocation_history_guid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_allocation',
            name='item_primary_key',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='temporary_allocation',
            name='item_primary_key',
            field=models.BigIntegerField(null=True),
        ),
    ]
