# Generated by Django 5.1.5 on 2025-08-21 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('warehouse', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Chittagong', 'Chittagong')], default='Dhaka', max_length=50)),
                ('unit_of_item', models.CharField(choices=[('Nos.', 'Nos.'), ('Mtr.', 'Mtr.'), ('Km.', 'Km.'), ('Set.', 'Set.'), ('Pair.', 'Pair.')], default='Nos.', max_length=10)),
                ('quantity_of_item', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_of_item', to='Project_App_Entry.project')),
            ],
        ),
    ]
