# Generated by Django 5.1.5 on 2025-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_Entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_item',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
