# Generated by Django 5.1.5 on 2025-08-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_Entry', '0002_project_item_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_item',
            name='quantity_of_item',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
