# Generated by Django 5.1.5 on 2025-08-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_Entry', '0003_alter_project_item_quantity_of_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_item',
            name='remarks_for_projectWWiseBalance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
