# Generated by Django 5.1.5 on 2025-08-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_Entry', '0004_project_item_remarks_for_projectwwisebalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_item',
            old_name='remarks_for_projectWWiseBalance',
            new_name='remarks_for_projectWiseBalance',
        ),
    ]
