# Generated by Django 5.1.5 on 2026-03-21 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PBSWise_Balance', '0005_remove_zonals_balance_unit_zonal_items_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBS_History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('action', models.CharField(choices=[('Transfer Item', 'Transfer Item'), ('Withdraw Item', 'Withdraw Item')], max_length=50)),
                ('store_from', models.CharField(max_length=100)),
                ('store_to', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='PBSWise_Balance.zonal_items')),
                ('pbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='PBSWise_Balance.pbs_list')),
                ('zonal_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_from', to='PBSWise_Balance.pbs_zonals')),
                ('zonal_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_to', to='PBSWise_Balance.pbs_zonals')),
            ],
            options={
                'verbose_name_plural': 'PBS History Logs',
                'ordering': ['-date'],
            },
        ),
    ]
