# Generated by Django 5.1.5 on 2025-08-22 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project_App_Entry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Allocation_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_no', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled'), ('Modified', 'Modified')], default='Pending Approval', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocation_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Final_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_primary_key', models.IntegerField(null=True)),
                ('unit_of_item', models.TextField()),
                ('warehouse', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_App_Allocation.allocation_number')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_App_Entry.project_item')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_App_Entry.project')),
                ('pbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_App_Allocation.pbs')),
            ],
        ),
        migrations.CreateModel(
            name='Temporary_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_primary_key', models.IntegerField(null=True)),
                ('unit_of_item', models.TextField()),
                ('warehouse', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_App_Allocation.allocation_number')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_App_Entry.project_item')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_App_Entry.project')),
                ('pbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project_App_Allocation.pbs')),
            ],
        ),
    ]
