# Generated by Django 5.1.5 on 2025-08-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_Allocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final_allocation',
            old_name='package',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='temporary_allocation',
            old_name='package',
            new_name='project',
        ),
    ]
