# Generated by Django 5.1.5 on 2025-08-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_Allocation', '0002_rename_package_final_allocation_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_allocation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='temporary_allocation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
