# Generated by Django 5.1.5 on 2025-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_Allocation', '0003_alter_final_allocation_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_allocation',
            name='status',
            field=models.CharField(default='Allocated', max_length=100),
        ),
    ]
