# Generated by Django 5.1.5 on 2025-08-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_Allocation', '0004_final_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_allocation',
            name='history_GUID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
