# Generated by Django 5.1.5 on 2025-08-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_Allocation', '0005_final_allocation_history_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_allocation',
            name='history_GUID',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
