# Generated by Django 5.1.5 on 2026-03-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBSWise_Summary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PBSWise_Summary',
        ),
    ]
