# Generated by Django 5.1.5 on 2026-02-14 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_pagination_limit', models.PositiveIntegerField(default=50)),
            ],
        ),
    ]
