# Generated by Django 5.1.5 on 2026-02-14 11:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin_Panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginationManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_pagination_limit', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SystemConfiguration',
        ),
    ]
