# Generated by Django 5.1.5 on 2025-02-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0002_alter_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
