# Generated by Django 5.1.5 on 2025-02-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0003_alter_package_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='package',
            name='unit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
