# Generated by Django 5.1.5 on 2025-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0004_remove_packageitem_unit_package_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='package',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_of_item',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Khulna', 'Khulna'), ('Chittagong', 'Chittagong')], default='Dhaka', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='packageId',
            field=models.CharField(default=23, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='PackageItem',
        ),
    ]
