# Generated by Django 5.1.5 on 2025-02-15 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0005_remove_package_description_remove_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_of_item', to='App_Entry.package'),
        ),
    ]
