# Generated by Django 5.1.5 on 2025-02-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0006_item_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.BigIntegerField(unique=True),
        ),
    ]
