# Generated by Django 5.1.5 on 2025-02-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0008_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
