# Generated by Django 5.1.5 on 2025-02-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0010_rename_quantity_item_quantity_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_of_item',
            field=models.CharField(choices=[('Nos.', 'Nos.'), ('Mtr.', 'Mtr.'), ('Km.', 'Km.'), ('Set.', 'Set.'), ('Pair.', 'Pair.')], default='Nos.', max_length=10),
        ),
    ]
