# Generated by Django 5.1.5 on 2025-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0013_alter_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='packageId',
            field=models.TextField(unique=True),
        ),
    ]
