# Generated by Django 5.1.5 on 2025-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0014_alter_package_packageid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_of_item',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
