# Generated by Django 5.1.5 on 2025-08-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Entry', '0015_alter_item_quantity_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_of_item',
            field=models.CharField(choices=[('Nos.', 'Nos.'), ('Mtr.', 'Mtr.'), ('Km.', 'Km.'), ('Set.', 'Set.'), ('Pair.', 'Pair.'), ('Kg', 'Kg'), ('Lot', 'Lot'), ('Pcs', 'Pcs'), ('Coil', 'Coil'), ('Box', 'Box'), ('Feet', 'Feet'), ('Liter', 'Liter'), ('m3', 'm3'), ('m2', 'm2'), ('Ream', 'Ream'), ('Bundle', 'Bundle'), ('Carton', 'Carton')], default='Nos.', max_length=10),
        ),
    ]
