# Generated by Django 5.1.5 on 2025-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_no', models.IntegerField()),
                ('pbs', models.TextField()),
                ('project', models.TextField()),
                ('item', models.TextField()),
                ('warehouse', models.CharField(max_length=50)),
                ('unit_of_item', models.TextField()),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled'), ('Modified', 'Modified')], default='Allocated', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('CS_and_M', models.DateTimeField(blank=True, null=True)),
                ('carry_from_warehouse', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
