# Generated by Django 5.1.5 on 2025-08-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_History', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Project_History',
        ),
    ]
