# Generated by Django 5.1.5 on 2025-08-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_History', '0002_rename_history_project_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_history',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
