# Generated by Django 5.1.5 on 2025-08-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_History', '0003_project_history_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_history',
            name='CS_and_M',
        ),
    ]
