# Generated by Django 5.1.5 on 2025-08-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_History', '0004_remove_project_history_cs_and_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_history',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
