# Generated by Django 5.1.5 on 2025-08-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_History', '0005_alter_project_history_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_history',
            name='GUID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
