# Generated by Django 5.1.5 on 2025-08-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_History', '0006_project_history_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_history',
            name='GUID',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
