# Generated by Django 5.1.5 on 2025-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_History', '0007_alter_project_history_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_history',
            name='remarks_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
