# Generated by Django 5.1.5 on 2025-08-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_History', '0008_project_history_remarks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_history',
            name='carry_from_warehouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
