# Generated by Django 5.1.5 on 2025-08-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_History', '0009_alter_project_history_carry_from_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_history',
            name='item_primary_key',
            field=models.BigIntegerField(null=True),
        ),
    ]
