# Generated by Django 5.1.5 on 2026-03-19 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBSWise_Balance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PBS_Zonals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zonal_name', models.CharField(max_length=256)),
                ('zonal_type', models.CharField(choices=[('HQ', 'HQ'), ('Zonal', 'Zonal'), ('Sub-Zonal', 'Sub-Zonal')], max_length=50)),
                ('pbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonals', to='PBSWise_Balance.pbs_list')),
            ],
        ),
    ]
