# Generated by Django 5.1.5 on 2026-03-20 18:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBSWise_Balance', '0002_pbs_zonals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonal_Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=256)),
            ],
        ),
    ]
