# Generated by Django 5.1.5 on 2026-03-20 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBSWise_Balance', '0003_zonal_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonals_Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('Nos.', 'Nos.'), ('Mtr.', 'Mtr.'), ('Km.', 'Km.'), ('Set.', 'Set.'), ('Pair.', 'Pair.'), ('Kg', 'Kg'), ('Lot', 'Lot'), ('Pcs', 'Pcs'), ('Coil', 'Coil'), ('Box', 'Box'), ('Feet', 'Feet'), ('Liter', 'Liter'), ('m3', 'm3'), ('m2', 'm2'), ('Ream', 'Ream'), ('Bundle', 'Bundle'), ('Carton', 'Carton')], default='Nos.', max_length=100)),
                ('deposit_work', models.FloatField(default=0.0)),
                ('mcep_dmd', models.FloatField(default=0.0)),
                ('mcep_kd', models.FloatField(default=0.0)),
                ('mcep_bd', models.FloatField(default=0.0)),
                ('other', models.FloatField(default=0.0)),
                ('om_store', models.FloatField(default=0.0)),
                ('own_stock', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0, editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonal_balances', to='PBSWise_Balance.zonal_items')),
                ('pbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonal_balances', to='PBSWise_Balance.pbs_list')),
                ('zonal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonal_balances', to='PBSWise_Balance.pbs_zonals')),
            ],
            options={
                'verbose_name_plural': 'Zonal Balances',
                'unique_together': {('pbs', 'zonal', 'item')},
            },
        ),
    ]
