# Generated by Django 5.1.5 on 2026-03-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBSWise_Balance', '0005_remove_zonals_balance_unit_zonal_items_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonals_balance',
            name='description',
        ),
        migrations.AddField(
            model_name='zonal_items',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
