# Generated by Django 5.1.5 on 2026-03-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBSWise_Balance', '0006_remove_zonals_balance_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonal_items',
            name='unit',
            field=models.CharField(choices=[('Nos.', 'Nos.'), ('Mtr.', 'Mtr.'), ('Km.', 'Km.'), ('Set.', 'Set.'), ('Pair.', 'Pair.'), ('Kg', 'Kg'), ('Lot', 'Lot'), ('Pcs', 'Pcs'), ('Coil', 'Coil'), ('Box', 'Box'), ('Feet', 'Feet'), ('Liter', 'Liter'), ('m3', 'm3'), ('m2', 'm2'), ('Ream', 'Ream'), ('Bundle', 'Bundle'), ('Carton', 'Carton'), ('Drum', 'Drum')], default='Nos.', max_length=100),
        ),
    ]
