# Generated by Django 5.1.5 on 2025-08-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_group',
            name='user_group_type',
            field=models.CharField(choices=[('View History and Status only', 'View History and Status only'), ('Editor', 'Editor'), ('Only View History and Edit CS&M Column', 'Only View History and Edit CS&M Column'), ('Only View History and Edit Carry_From_Warehouse Column', 'Only View History and Edit Carry_From_Warehouse Column')], default='View History and Status only', max_length=100),
        ),
    ]
