# Generated by Django 5.1.5 on 2025-08-05 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_alter_user_group_user_group_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_group',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_group',
            name='user_group_type',
            field=models.CharField(choices=[('View History and Status only', 'View History and Status only'), ('Editor', 'Editor'), ('Only_View_History_and_Edit_CS&M_Column', 'OnlyView History and Edit CS&M Column'), ('Only_View_History_and_Edit_Carry_From_Warehouse_Column', 'Only View History and Edit Carry_From_Warehouse Column')], default='View History and Status only', max_length=100),
        ),
    ]
