# Generated by Django 5.1.5 on 2026-03-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0004_alter_user_group_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_group',
            name='user_group_type',
            field=models.CharField(choices=[('View History and Status only', 'View History and Status only'), ('Editor', 'Editor'), ('Only_View_History_and_Edit_CS&M_Column', 'OnlyView History and Edit CS&M Column'), ('Only_View_History_and_Edit_Carry_From_Warehouse_Column', 'Only View History and Edit Carry_From_Warehouse Column'), ('Specific_PBS_Account', 'Specific PBS Account')], default='View History and Status only', max_length=100),
        ),
    ]
