# Generated by Django 5.1.5 on 2026-03-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_alter_user_group_user_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_group',
            name='cleartext_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
