# Generated by Django 5.1.5 on 2025-08-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project_App_Entry', '0003_alter_project_item_quantity_of_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_W_Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_entries', to='Project_App_Entry.project_item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_entries', to='Project_App_Entry.project')),
            ],
            options={
                'unique_together': {('project', 'item')},
            },
        ),
    ]
