# Generated by Django 5.1.5 on 2025-08-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project_App_ProjectWiseBalance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_W_Balance',
        ),
    ]
