# Generated by Django 5.1.5 on 2025-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.TextField(default='Allocated'),
            preserve_default=False,
        ),
    ]
