# Generated by Django 5.1.5 on 2025-04-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0003_alter_history_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled'), ('Modified', 'Modified')], default='Allocated', max_length=100),
        ),
    ]
