# Generated by Django 5.1.5 on 2025-04-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0004_remove_history_created_at_alter_history_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
