# Generated by Django 5.1.5 on 2025-08-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0005_history_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='CS_and_M',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='carry_from_warehouse',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
