# Generated by Django 5.1.5 on 2025-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0006_history_cs_and_m_history_carry_from_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='package',
            field=models.TextField(),
        ),
    ]
