# Generated by Django 5.1.5 on 2025-08-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0007_alter_history_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='unit',
            field=models.TextField(default='Mtr.'),
            preserve_default=False,
        ),
    ]
