# Generated by Django 5.1.5 on 2025-08-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0008_history_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='unit',
            new_name='unit_of_item',
        ),
    ]
