# Generated by Django 5.1.5 on 2025-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0009_rename_unit_history_unit_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
