# Generated by Django 5.1.5 on 2025-08-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0010_alter_history_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='GUID',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
