# Generated by Django 5.1.5 on 2025-08-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0011_history_guid'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='remarks_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
