# Generated by Django 5.1.5 on 2025-08-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0012_history_remarks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='carry_from_warehouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
