# Generated by Django 5.1.5 on 2025-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0013_alter_history_carry_from_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='CS_and_M',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
