# Generated by Django 5.1.5 on 2025-08-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_History', '0014_alter_history_cs_and_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
